id: P004629
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN5402
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིགས་པ།
  author: ''
  volumes:
    2748ddcf81944002a6f984254dae0f44:
      image_group_id: I3CN5404
      title: ''
      volume_number: 1
      total_pages: 398
      base_file: v001.txt
