id: P004629
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5402
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཚིག་འགྲེལ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིགས་པ།
  author: ''
  volumes: {}
